<?php 
    $config = Mage::getStoreConfig('mdloption/homeproducts');
    $categoryId = $config['featured'];
	$cObj = Mage::getModel('catalog/category')->load($categoryId);
	
	$visibility = array(
            Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
            Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
        );
	$productObj = $cObj->getProductCollection()->addAttributeToFilter('visibility', $visibility)->getData();
    $_helper = $this->helper('catalog/output');
?>
<?php if($config['featuredsetting']):?>
<?php if(count($productObj)<=0): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="headingBox"> <span class="headingIcons featuredIcon"></span>
  <h2 class="line_heading"><?php echo $this->__('Featured Products')?></h2>
</div>
<div id="mix_container" class="mix_container featuredbox rowMin">
  <div class="mix_wrapper">
    <div class="mix_inner">
      <div class="featured" id="owl-demo">
        <?php $i=1;foreach($productObj as $_productData): ?>
        <?php $_product = Mage::getModel('catalog/product')->load($_productData['entity_id']); ?>
        <div class="item">
          <div class="itemInner">
            <div class="badge">
              <?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
              <?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
            </div>
            <?php if($config['featured_quick_view']==1):?>
            <a  rel="tooltip" data-placement="top" title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick_view' id='fancybox<?php echo $_product->getId();?>'><i class="icon-search"></i></a>
            <?php endif; ?>
            <?php if($config['featured_flip_view']==1):?>
            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220,215); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"  /> <img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(220); ?>" alt="<?php echo $this->htmlEscape($_product['name']); ?>" border="0" /> </a>
            <?php else: ?>
            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220,215); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> </a>
            <?php endif; ?>
            <!--first view-->
            <?php if($config['itemviewbox']==0):?>
            <div class="ic_caption">
              <h2 class="product-name"> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"> <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> </a> </h2>
              <div class="seb1"> <?php echo $this->getPriceHtml($_product, true, '-right') ?> <?php echo $this->getReviewsSummaryHtml($_product, false, true)?> </div>
              <div class="bottomBox">
               
                  <!--Quick view-->
                  <?php if($config['featured_quick_view']==1):?>
                  <?php if($_product->isSaleable()): ?>
                  <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
                  <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
                  <?php else: ?>
                  <a title="<?php echo $this->__('Add to Cart') ?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox btn' id='fancybox<?php echo $_product->getId();?>'><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></a>
                  <?php endif; ?>
                  <?php else: ?>
                  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?>
                  <?php else: ?>
                  <?php if($_product->isSaleable()): ?>
                 
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
                 
                  <?php else: ?>
                  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?>
                  <?php endif; ?>
                  <!--end quick view-->
                  
                  <div class="addtobox">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top" class="link-wishlist"><i class="icon-heart"></i></a>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                    <a class="compareR" href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" > <i class="icon-exchange"></i> </a>
                    <?php endif; ?>
                  </div>
              
              </div>
            </div>
            <?php else: ?>
            <!--second view-->
            <div class="ic_caption box2">
              <h2 class="product-name"> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"> <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> </a> </h2>
              <div class="seb1"><?php echo $this->getPriceHtml($_product, true, '-right') ?> <?php echo $this->getReviewsSummaryHtml($_product, false, true)?></div>
              <div class="bottomBox">
                <?php if($config['featured_quick_view']==1):?>
                  <?php if($_product->isSaleable()): ?>
                  <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
                  <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
                  <?php else: ?>
                  <a title="<?php echo $this->__('Add to Cart') ?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox btn' id='fancybox<?php echo $_product->getId();?>'><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></a>
                  <?php endif; ?>
                  <?php else: ?>
                  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?>
                  <?php else: ?>
                   <?php if($_product->isSaleable()): ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
                 
                  <?php else: ?>
                  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?>
                   <?php endif; ?>
                  <ul class="addBox2">
                    <li class="link-wishlist2">
                      <?php if ($this->helper('wishlist')->isAllow()) : ?>
                      <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top"><i class="icon-plus-sign-alt"></i> <?php echo $this->__('Wishlist') ?></a>
                      <?php endif; ?>
                    </li>
                    <li class="compareR2">
                      <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                      <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" > <i class="icon-plus-sign-alt"></i> <?php echo $this->__('Compare') ?> </a>
                      <?php endif; ?>
                    </li>
                  </ul>
              </div>
            </div>
            <?php endif; ?>
          </div>
        </div>
        <?php endforeach ?>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class=" sliderNab customNavigation">
         <a class="jcarousel-next prev"><i class="icon-angle-right"></i></a>
         <a class="jcarousel-next next"><i class="icon-angle-left"></i></a>
    </div>
  </div>
</div>
<script type="text/javascript">
  jQuery(document).ready(function() {     
        var owl = jQuery("#owl-demo");
	    owl.owlCarousel({
			items : <?php echo $config['featuredItem'];?>
		});
		// Custom Navigation Events
		jQuery(".next").click(function(){
			owl.trigger('owl.next');
		})
		jQuery(".prev").click(function(){
			owl.trigger('owl.prev');
		})     
	 });
</script>
<?php endif; ?>
<?php endif; ?>