<?php
    $_productCollection=$this->getLoadedProductCollection();
    $columnCount = mdlList('column_count');
    $this->setColumnCount($columnCount);
    $_helper = $this->helper('catalog/output');   
    
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<?php $config = Mage::getStoreConfig('mdloption/item_view_cat');?>
<div class="category-products row-fluid">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <?php $imgSize = 192; ?>
    <ol class="products-list itemPro" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
           <div class="productListInner col-sm-4"> 
            <div class="badge">			
            <?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
            <?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
          </div>
           <?php if($config['itemviewbox_quick_view']==1):?>
            <a  rel="tooltip" data-placement="top" title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick_view' id='fancybox<?php echo $_product->getId();?>'><i class="icon-search"></i></a>
            <?php endif; ?>     
           
          <?php if($config['flip_viewcat']==1):?>
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
         <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220,215); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"  />
          <img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(220); ?>" alt="<?php echo $this->htmlEscape($_product['name']); ?>" border="0" />
          </a>
          <?php else: ?>
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
          <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220,215); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
          </a>
          <?php endif; ?>
            </div>   
            <?php // Product description ?>
            <div class="product-shop col-sm-8">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    
                    <?php if($_product->getRatingSummary()): ?>
                    	<?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                      
                    <div class="bottomBox">
                    <?php if($config['itemviewbox_quick_view']==1):?>
                    <?php if($_product->isSaleable()): ?>
                    	 <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
                           <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
                         <?php else: ?>
                           <a title="<?php echo $this->__('Add to Cart') ?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox btn' id='fancybox<?php echo $_product->getId();?>'><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></a>
                         <?php endif; ?>
                          
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <?php else: ?>
                    <?php if($_product->isSaleable()): ?>
                  <p>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                  </p>
                  <?php else: ?>
                  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?>
                     <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li class="link-wishlist2"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top" class="link-wishlist"><i class="icon-plus-sign-alt"></i><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li class="compareR2"><a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" class="link-compare"><i class="icon-plus-sign-alt"></i><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
     <?php 
    
        $_columnCount = $this->getColumnCount(); 
        
        if($_columnCount == 4){
			$listWidth = 'col-sm-3';
            $imgSize = 155;
        }elseif($_columnCount == 3){
			$listWidth = 'col-sm-4';
            $imgSize = 245;
      } 
    ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid itemPro">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> <?php echo $listWidth; ?>">
            <div class="itemInner">
       <div class="badge">			
            <?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
            <?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
       </div>
           	
            <?php if($config['itemviewbox_quick_view']==1):?>
            <a  rel="tooltip" data-placement="top" title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick_view' id='fancybox<?php echo $_product->getId();?>'><i class="icon-search"></i></a>
            <?php endif; ?>   
            
       <?php if($config['flip_viewcat']==1):?>
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image" rel="gallery">
         <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220,215); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"  />
          <img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(220); ?>" alt="<?php echo $this->htmlEscape($_product['name']); ?>" border="0" />
          </a>
          <?php else: ?>
          <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
          <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220,215); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
          </a>
          <?php endif; ?>
          
          
          
          <!--first view-->
          <?php if($config['itemviewboxcat']==0):?>
              <div class="ic_caption">
                <h2 class="product-name">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                    </a>
                </h2>
            
                   <div class="seb1">
                   		<?php echo $this->getPriceHtml($_product, true, '-right') ?>
                    	<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                   </div>       
                    <div class="bottomBox"> 
 
                     <?php if($config['itemviewbox_quick_view']==1):?>     
                    <?php if($_product->isSaleable()): ?>
                    	 <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
                           <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
                         <?php else: ?>
                           <a title="<?php echo $this->__('Add to Cart') ?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox btn' id='fancybox<?php echo $_product->getId();?>'><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></a>
                         <?php endif; ?>
                          
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <?php else: ?>
                    <?php if($_product->isSaleable()): ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                  <?php else: ?>
                      <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?>
                      <?php endif; ?>
                  
                    
                    	
                        <div class="addtobox">
                         <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top" class="link-wishlist"><i class="icon-heart"></i></a>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <a class="compareR" href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" >
                            	<i class="icon-exchange"></i>
                            </a>
                        <?php endif; ?>
                        </div>
               
                    
                    </div>
               </div>  
          <?php else: ?> 
          <!--second view-->
             <div class="ic_caption box2">
                <h2 class="product-name">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                    </a>
                </h2>
            
                   <div class="seb1">
                   	<?php echo $this->getPriceHtml($_product, true, '-right') ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                   </div>       
                    <div class="bottomBox"> 
                     <?php if($config['itemviewbox_quick_view']==1):?>           
                    <?php if($_product->isSaleable()): ?>
                    	 <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
                           <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
                         <?php else: ?>
                           <a title="<?php echo $this->__('Add to Cart') ?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox btn' id='fancybox<?php echo $_product->getId();?>'><i class="icon-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></a>
                         <?php endif; ?>
                          
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <?php else: ?>
                    <?php if($_product->isSaleable()): ?>
                  <p>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                  </p>
                  <?php else: ?>
                  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                  <?php endif; ?>
                    <?php endif; ?>
                    
                  <ul class="addBox2">
                  	<li class="link-wishlist2">
                         <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip" data-placement="top"><i class="icon-plus-sign-alt"></i> <?php echo $this->__('Wishlist') ?></a>
                        <?php endif; ?>
                    </li>
                    <li class="compareR2">  
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip" data-placement="top" >
                            	<i class="icon-plus-sign-alt"></i> <?php echo $this->__('Compare') ?>
                            </a>
                        <?php endif; ?>
                    </li>
                    </ul>
                     
                    
                    </div>
               </div>  
          <?php endif; ?>
     
          </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
<script type="text/javascript">
	jQuery(window).scroll(function(){
	    jQuery("[rel=tooltip]").tooltip();
	});
</script>
